### ISSUE TITLE
panic when battery at 100% but not charging

### ISSUE THREAD

**Issue by rszyma** [drdeimos/go_battery_notifier#2]
```
panic: runtime error: index out of range [10] with length 10

goroutine 1 [running]:
main.polybar_out(0x4059000000000000, 0x4)
        /home/n/go/src/polybar_another_battery/polybar_ab.go:204 +0x831
main.main()
        /home/n/go/src/polybar_another_battery/polybar_ab.go:106 +0x9a9
exit status 2
```

**Comment by drdeimos** [comment]
https://github.com/drdeimos/polybar_another_battery/commit/65353a1608d7cf50666f7ef29797277ac66d82fc - that can be help.

**Comment by rszyma** [comment]
Yep, that fixes it. 

By the way, do you know which font polybar needs in order to display these battery unicode characters?

**Comment by drdeimos** [comment]
>(Run) Font for battery indicator - 3270Medium NF

Some time ago i found this icons in this font.
But now i use this fonts for last build:
```
font-0 = DejaVu Sans Mono:style=Book:pixelsize=8;1
font-1 = unifont:fontformat=truetype:size=6:antialias=false;0
font-2 = siji:pixelsize=10;1
font-3 = 3270Medium NF::pixelsize=8;1
```
